dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=budy setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: CnGBUBm8oNBSzYJAHOaaE5Txf8711Qhrrge5qtuQjGeY0GlIQdQhxwO2RAYzEQ/IAdxz/Muz0A/q0TC7olTEDunqgQPPDnbI+tD/U8pvVoqpnCJLhDj2Fa9dQf2I3/VUdR0W5gws93NsKL99p91yE4YJfnGTZpXRbxnSVVB3gqk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
