sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: coverage run --source=budy setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: CnGBUBm8oNBSzYJAHOaaE5Txf8711Qhrrge5qtuQjGeY0GlIQdQhxwO2RAYzEQ/IAdxz/Muz0A/q0TC7olTEDunqgQPPDnbI+tD/U8pvVoqpnCJLhDj2Fa9dQf2I3/VUdR0W5gws93NsKL99p91yE4YJfnGTZpXRbxnSVVB3gqk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
