from typing import Any, Dict

class AccountAPI:
    def list_accounts(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_account(
        self, payload: Dict[str, Any], pre_enabled: bool = ...
    ) -> Any: ...
    def recover_account(self, username: str) -> Any: ...
    def reset_account(self, username: str, password: str, token: str) -> Any: ...
    def me_account(self) -> Any: ...
    def update_me_account(self, payload: Dict[str, Any]) -> Any: ...
    def avatar_me_account(self) -> Any: ...
    def orders_me_account(self) -> Any: ...
    def addresses_me_account(self) -> Any: ...
    def create_addresses_me_account(self, payload: Dict[str, Any]) -> Any: ...
    def delete_address_me_account(self, key: str) -> Any: ...
    def confirm_account(self, token: str) -> Any: ...
