from typing import Any, Dict


class AddressAPI:
    def list_addresses(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_address(self, payload: Dict[str, Any]) -> Any: ...
    def get_address(self, key: str) -> Any: ...
    def update_address(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def delete_address(self, key: str) -> Any: ...
