from typing import Any, Dict

class BagAPI:
    def list_bags(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_bag(self, payload: Dict[str, Any]) -> Any: ...
    def key_bag(self) -> Any: ...
    def get_bag(self, key: str) -> Any: ...
    def merge_bag(self, key: str, target: str) -> Any: ...
    def add_line_bag(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def remove_line_bag(self, key: str, line_id: int) -> Any: ...
    def add_update_line_bag(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def empty_bag(self, key: str) -> Any: ...
    def order_bag(self, key: str) -> Any: ...
