from typing import Any, Dict


class OrderAPI:
    def list_orders(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_order(self, key: str) -> Any: ...
    def set_store_order(self, key: str, store_id: int) -> Any: ...
    def set_shipping_address_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def set_billing_address_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def set_store_shipping_order(self, key: str) -> Any: ...
    def set_store_billing_order(self, key: str) -> Any: ...
    def set_ip_address_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def set_email_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def set_gift_wrap_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def set_referral_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def set_voucher_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def set_meta_order(self, key: str, name: str, value: str) -> Any: ...
    def set_account_order(self, key: str) -> Any: ...
    def wait_payment_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def pay_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def end_pay_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
    def cancel_order(self, key: str, payload: Dict[str, Any]) -> Any: ...
