from typing import Any


class ProductAPI:
    def list_products(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_product(self, id: int) -> Any: ...
    def search_products(self, *args: Any, **kwargs: Any) -> Any: ...
    def related_product(self, id: int, *args: Any, **kwargs: Any) -> Any: ...
    def share_product(self, id: int, *args: Any, **kwargs: Any) -> Any: ...
    def quote_product(self, id: int, *args: Any, **kwargs: Any) -> Any: ...
