from typing import Any


class SeasonAPI:
    def list_seasons(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_season(self, id: int) -> Any: ...
    def slug_season(self, slug: str) -> Any: ...
